name: Build Corne VIAL firmware
on: [push, workflow_dispatch]

jobs:
  build:
    name: Build crkbd vial firmware
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure git safe directory
        run: git config --global --add safe.directory $(pwd)

      - name: Build firmware
        run: qmk compile -kb crkbd -km vial

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: crkbd-vial-firmware
          path: |
            *.hex
            *.uf2
