name: Build Corne VIAL firmware
on: [push, workflow_dispatch]

jobs:
  build:
    name: Build crkbd vial firmware
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure git safe directory
        run: git config --global --add safe.directory $(pwd)

      - name: Prepare output dir
        run: mkdir -p output

      - name: Build LEFT firmware
        run: |
          rm -rf .build
          qmk compile -kb crkbd -km vial -e "EXTRAFLAGS=-DINIT_EE_HANDS_LEFT"
          mv crkbd_rev1_vial.hex output/crkbd_vial_left.hex

      - name: Build RIGHT firmware
        run: |
          rm -rf .build
          qmk compile -kb crkbd -km vial -e "EXTRAFLAGS=-DINIT_EE_HANDS_RIGHT"
          mv crkbd_rev1_vial.hex output/crkbd_vial_right.hex

      - name: List artifacts
        run: ls -la output/

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: crkbd-vial-firmware
          path: |
            output/crkbd_vial_left.hex
            output/crkbd_vial_right.hex
